# Source size (src/*): ~191.1 KB
[build-system]
requires = [
    "hatchling",
]
build-backend = "hatchling.build"

[project]
name = "xwformats"
dynamic = [
    "version",
]
description = "Convenience wrapper for exonware-xwformats - provides 'import xwformats' alias"
readme = "README.md"
requires-python = ">=3.8"
keywords = []
classifiers = []
dependencies = [
    "exonware-xwformats",
]
authors = [
    { name = "Eng. Muhammad AlShehri", email = "connect@exonware.com" },
]

[project.license]
text = "MIT"

[project.optional-dependencies]
lazy = [
    "exonware-xwformats[lazy]",
]
dev = [
    "exonware-xwformats[dev]",
]
full = [
    "exonware-xwformats[full]",
]

[project.urls]
Homepage = "https://exonware.com"
Repository = "https://github.com/exonware/xwformats"
Documentation = "https://github.com/exonware/xwformats#readme"

[tool.hatch.version]
path = "src/exonware/xwformats/version.py"

[tool.hatch.build.targets.wheel]
only-include = [
    "README.md",
    "src/xwformats_wrapper.py",
]

[tool.hatch.build.targets.sdist]
include = [
    "/src",
    "/tests",
    "/README.md",
    "/.github",
]
