version = "1.0"
generated = "2026-01-10T22:25:29.562023"
packages = [
    "capnp",
    "google",
    "numpy",
    "pyarrow",
    "scipy",
    "snappy",
    "zope",
]

[statistics]
total_installs = 26
total_failures = 0
